[managed_nodes]
node1 ansible_host=192.168.56.104 ansible_user=leroy1 apache_package=apache2 php_package=libapache2-mod-php 
node2 ansible_host=192.168.56.106 ansible_user=leroy1 apache_package=apache2 php_package=libapache2-mod-php
centos ansible_host=192.168.56.107 ansible_user=sysadleroy1 apache_package=httpd php_package=php

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_scp_extra_args="-O"
ansible_transfer_method=pipelining
