[web_servers]
ubuntu-node ansible_host=192.168.56.104 ansible_user=leroy1
centos-node ansible_host=192.168.56.107 ansible_user=sysadleroy1

[workstations]
ubuntu-node ansible_host=192.168.56.104 ansible_user=leroy1

[db_servers]
centos-node ansible_host=192.168.56.107 ansible_user=sysadleroy1

[file_servers]
ubuntu-node ansible_host=192.168.56.104 ansible_user=leroy1
